---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Untitled Diagram/Untitled Diagram.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/80989/articles/200071/master/file/figures/Untitled%20Diagram/Untitled%20Diagram.png"
